"""
Node graph's CanvasSettings -> conky.conf.

Structure and defaults mirror the validated conky.conf from the Batman
theme: self-locating THEME_DIR via debug.getinfo (so the theme folder is
relocatable -- install it anywhere, drag it to another machine, it just
works), an empty conky.text (100% of the visible HUD comes from Lua/
Cairo, nothing from Conky's own TEXT renderer), and a lua_draw_hook_post
rather than _pre (draws after Conky's own pass, which is what the
original was actually tested with).

window_type resolution (auto / normal / desktop / dock) is decided by
hardware.discovery before this module is called -- this module only
formats whatever was decided, it doesn't detect anything itself.
"""
from __future__ import annotations

from conkystudio.model.project import Project
from conkystudio.codegen.lua_gen import has_clickable_nodes

_WINDOW_HINTS = {
    "normal": "undecorated,below,sticky,skip_taskbar,skip_pager",
    "desktop": "undecorated,below,sticky,skip_taskbar,skip_pager",
    "dock": "undecorated,below,sticky,skip_taskbar,skip_pager",
}


def build_conky_conf(project: Project, resolved_window_type: str, wayland_note: str = "") -> str:
    c = project.canvas
    win_type = resolved_window_type if resolved_window_type in ("normal", "desktop", "dock") else "normal"
    hints = _WINDOW_HINTS[win_type]
    argb = "true" if c.transparent else "false"
    transparent = "false" if c.transparent else "true"  # legacy transparent hack, mutually exclusive w/ ARGB
    update_interval = round(1.0 / max(1, c.fps), 4)
    mouse_hook_line = "    lua_mouse_hook = 'mouse_handler',\n" if has_clickable_nodes(project) else ""

    header = f'''-- =====================================================================
--  {project.name}
--  Generated by Conky Studio -- editing this file directly is fine, but
--  re-opening the .cstudio project and clicking Build & Run will
--  overwrite it with a fresh copy from the node graph.
-- ---------------------------------------------------------------------
{("--  " + wayland_note) if wayland_note else ""}
-- =====================================================================

conky.config = {{
    -- Self-locating: THEME_DIR resolves relative to *this file*, so the
    -- theme keeps working no matter where it's installed.
    lua_load = (function()
        local src = debug.getinfo(1, 'S').source:gsub('^@', '')
        local dir = (src:match('(.*/)') or './'):gsub('/$', '')
        return dir .. '/render.lua'
    end)(),
    lua_draw_hook_post = 'main_draw',
{mouse_hook_line}
    own_window = true,
    own_window_type = '{win_type}',
    own_window_hints = '{hints}',
    own_window_class = '{c.window_class}',
    own_window_argb_visual = {argb},
    own_window_argb_value = 0,
    own_window_transparent = {transparent},

    alignment = '{c.alignment}',
    gap_x = {c.gap_x},
    gap_y = {c.gap_y},
    minimum_width = {c.width},
    minimum_height = {c.height},
    maximum_width = {c.width},

    background = false,
    total_run_times = 0,
    update_interval = {update_interval},

    use_xft = true,
    font = 'Sans:size=10',
    default_color = 'FFFFFF',
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    double_buffer = true,
    no_buffers = true,
}}

conky.text = [[]]
'''
    return header
