"""
Node graph window settings -> conky.conf (one file per window).

Structure and defaults mirror the validated conky.conf from the Batman
theme: self-locating THEME_DIR via debug.getinfo (so the theme folder is
relocatable), an empty conky.text, and lua_draw_hook_post.

Multi-window: builder writes conky.conf (primary) plus conky_<id>.conf for
additional windows. Each conf loads the same render.lua (shared graph) or
a filtered variant when visible_node_ids is set. xinerama_head pins a
window to a monitor when discovery resolves a concrete output index.
"""
from __future__ import annotations

import re

from conkystudio.model.project import Project, WindowSettings
from conkystudio.codegen.lua_gen import has_clickable_nodes

_WINDOW_HINTS = {
    "normal": "undecorated,below,sticky,skip_taskbar,skip_pager",
    "desktop": "undecorated,below,sticky,skip_taskbar,skip_pager",
    "dock": "undecorated,below,sticky,skip_taskbar,skip_pager",
}


def build_conky_conf(
    project: Project,
    resolved_window_type: str,
    wayland_note: str = "",
    *,
    window: WindowSettings | None = None,
    lua_basename: str = "render.lua",
    conf_title_suffix: str = "",
    xinerama_head: int | None = None,
    monitor_note: str = "",
    extra_directives: dict | None = None,
) -> str:
    """Emit one conky.conf body.

    When *window* is None, uses project.canvas (legacy single-window path).
    *xinerama_head* is 0-based output index for Conky's xinerama_head setting
    when a concrete monitor was resolved; None omits the setting.
    *extra_directives* is a flat key -> literal-value-text dict (typically
    from plugins.loader.resolve_canvas_ext_directives) written as-is just
    before the closing brace. Every key in it is already checked against
    plugins.schema.CANVAS_EXT_ALLOWED_KEYS at plugin-registration time, so
    this function trusts the caller and does no further whitelisting --
    it never accepts a key that collides with one of the fixed settings
    below (those are emitted first and would simply be shadowed/duplicated
    by Conky's own "last one wins" conf parsing, which is why canvas_ext
    plugins are validated against a key list disjoint from this function's
    own).
    """
    if window is not None:
        width = window.width
        height = window.height
        alignment = window.alignment
        gap_x = window.gap_x
        gap_y = window.gap_y
        fps = window.fps
        transparent = window.transparent
        window_class = window.window_class
        name_bit = window.name or window.id
    else:
        c = project.canvas
        width, height = c.width, c.height
        alignment, gap_x, gap_y = c.alignment, c.gap_x, c.gap_y
        fps, transparent = c.fps, c.transparent
        window_class = c.window_class
        name_bit = "Main"

    win_type = resolved_window_type if resolved_window_type in ("normal", "desktop", "dock") else "normal"
    hints = _WINDOW_HINTS[win_type]
    argb = "true" if transparent else "false"
    own_transparent = "false" if transparent else "true"
    update_interval = round(1.0 / max(1, fps), 4)
    mouse_hook_line = "    lua_mouse_hook = 'mouse_handler',\n" if has_clickable_nodes(project) else ""

    xinerama_line = ""
    if xinerama_head is not None and xinerama_head >= 0:
        xinerama_line = f"    xinerama_head = {int(xinerama_head)},\n"

    notes = []
    if wayland_note:
        notes.append("--  " + wayland_note)
    if monitor_note:
        notes.append("--  " + monitor_note)
    note_block = ("\n".join(notes) + "\n") if notes else ""

    title = project.name
    if conf_title_suffix:
        title = f"{project.name} — {conf_title_suffix}"
    elif window is not None and name_bit:
        title = f"{project.name} — {name_bit}"

    lines = []
    lines.append("-- =====================================================================")
    lines.append(f"--  {title}")
    lines.append("--  Generated by Conky Studio -- editing this file directly is fine, but")
    lines.append("--  re-opening the .cstudio project and clicking Build & Run will")
    lines.append("--  overwrite it with a fresh copy from the node graph.")
    lines.append("-- ---------------------------------------------------------------------")
    if note_block:
        lines.append(note_block.rstrip("\n"))
    lines.append("-- =====================================================================")
    lines.append("")
    lines.append("conky.config = {")
    lines.append("    -- Self-locating: THEME_DIR resolves relative to *this file*, so the")
    lines.append("    -- theme keeps working no matter where it is installed.")
    lines.append("    lua_load = (function()")
    lines.append("        local src = debug.getinfo(1, 'S').source:gsub('^@', '')")
    lines.append("        local dir = (src:match('(.*/)') or './'):gsub('/$', '')")
    lines.append(f"        return dir .. '/{lua_basename}'")
    lines.append("    end)(),")
    lines.append("    lua_draw_hook_post = 'main_draw',")
    if mouse_hook_line:
        lines.append(mouse_hook_line.rstrip("\n"))
    if xinerama_line:
        lines.append(xinerama_line.rstrip("\n"))
    lines.append("    own_window = true,")
    lines.append(f"    own_window_type = '{win_type}',")
    lines.append(f"    own_window_hints = '{hints}',")
    lines.append(f"    own_window_class = '{window_class}',")
    lines.append(f"    own_window_argb_visual = {argb},")
    lines.append("    own_window_argb_value = 0,")
    lines.append(f"    own_window_transparent = {own_transparent},")
    lines.append("")
    lines.append(f"    alignment = '{alignment}',")
    lines.append(f"    gap_x = {gap_x},")
    lines.append(f"    gap_y = {gap_y},")
    lines.append(f"    minimum_width = {width},")
    lines.append(f"    minimum_height = {height},")
    lines.append(f"    maximum_width = {width},")
    lines.append("")
    lines.append("    background = false,")
    lines.append("    total_run_times = 0,")
    lines.append(f"    update_interval = {update_interval},")
    lines.append("")
    lines.append("    use_xft = true,")
    lines.append("    font = 'Sans:size=10',")
    lines.append("    default_color = 'FFFFFF',")
    lines.append("    draw_shades = false,")
    lines.append("    draw_outline = false,")
    lines.append("    draw_borders = false,")
    lines.append("    draw_graph_borders = false,")
    lines.append("")
    lines.append("    double_buffer = true,")
    lines.append("    no_buffers = true,")
    if extra_directives:
        lines.append("")
        lines.append("    -- Added by canvas_ext plugin(s):")
        for key in sorted(extra_directives):
            value = extra_directives[key]
            # Numeric/bool-looking values are emitted unquoted (Conky reads
            # them as Lua literals); anything else is a quoted string.
            if re.fullmatch(r"-?\d+(\.\d+)?", value) or value in ("true", "false"):
                lines.append(f"    {key} = {value},")
            else:
                escaped = value.replace("\\", "\\\\").replace("'", "\\'")
                lines.append(f"    {key} = '{escaped}',")
    lines.append("}")
    lines.append("")
    lines.append("conky.text = [[]]")
    lines.append("")
    return "\n".join(lines)


def safe_conf_basename(window: WindowSettings, *, is_primary: bool) -> str:
    """Primary window keeps conky.conf for single-monitor compatibility.
    Extra windows get conky_<safe_id>.conf."""
    if is_primary:
        return "conky.conf"
    safe = "".join(ch if ch.isalnum() else "_" for ch in window.id).strip("_") or "extra"
    return f"conky_{safe}.conf"
