"""
Data-source node properties -> polling shell scripts.

Every generated script here is dual-mode, controlled by an optional
`--key NAME` argument:

  script.sh --key cpu_temp    execi mode: computes everything, prints
                               ONLY that one value to stdout, does no
                               file I/O. What ${execi N script.sh --key
                               cpu_temp} calls.

  script.sh                   daemon mode: computes everything, then
                               writes the full flock-guarded, atomically-
                               replaced key=value cache file -- exactly
                               sensors.sh / weather.sh's own pattern.
                               What start.sh's background polling loop
                               calls.

One script per script_family (see nodes.registry.NodeSpec.script_family),
built once from whichever node in that family the project actually has
(if two nodes in the same family disagree on an override like the AMD
DRM card, the first one wins -- Conky Studio doesn't currently surface
that as a conflict warning, which is a fair thing to improve later).
"""
from __future__ import annotations

from conkystudio.model.project import Project
from conkystudio.nodes import registry

_SHEBANG_HEADER = "#!/usr/bin/env bash\n# Generated by Conky Studio -- adapted from sensors.sh / weather.sh.\nset -o pipefail\n\n"


def _sh_sq(value) -> str:
    """POSIX-safe single-quoted shell literal for splicing an arbitrary
    (possibly quote-containing) user-editable value into a generated
    script as one shell word: close the quote, emit an escaped literal
    quote, reopen the quote. Every free-text node property that ends up
    inside one of these heredocs (chip_pattern regex, AMD card override,
    disk device path, weather fallback location, player name, album-art
    fallback path) MUST go through this -- an un-escaped `'` or `"` in
    any of them is exactly what turns into a shell "Unterminated quoted
    string" error at runtime instead of a build-time failure, since none
    of these are validated against shell metacharacters when the user
    types them into the Properties panel."""
    s = "" if value is None else str(value)
    return "'" + s.replace("'", "'\\''") + "'"


_CACHE_DIR_BOILERPLATE = '''SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/.runtime-cache"
CACHE_FILE="${CACHE_DIR}/%(family)s.cache"
TMP_FILE="${CACHE_FILE}.tmp"

PRINT_KEY=""
if [[ "$1" == "--key" ]]; then PRINT_KEY="$2"; fi
'''


def _atomic_write_footer(family: str, kv_lines: str, print_case: str) -> str:
    return f'''
if [[ -n "$PRINT_KEY" ]]; then
    case "$PRINT_KEY" in
{print_case}
        *) echo "" ;;
    esac
    exit 0
fi

mkdir -p "$CACHE_DIR"
exec 200>"${{CACHE_DIR}}/.{family}.lock"
flock -w 5 200 || exit 0
{{
    echo "updated=$(date +%s)"
{kv_lines}
}} > "$TMP_FILE" && mv "$TMP_FILE" "$CACHE_FILE"
'''


def _first_node_props(project: Project, family: str) -> dict:
    for n in project.nodes:
        spec = registry.get(n.type)
        if spec.script_family == family:
            return n.props
    return {}


# --------------------------------------------------------------- CPU sensors
def gen_cpu_sensors_script(project: Project) -> str:
    props = _first_node_props(project, "cpu_sensors")
    chip_pattern = props.get("chip_pattern", "^(coretemp-|k10temp-|cpu_thermal-|zenpower-)")

    body = f'''
CPU_TEMP_CHIP_PATTERN={_sh_sq(chip_pattern)}

CPU_TEMP=""
if command -v sensors >/dev/null 2>&1; then
    CPU_TEMP="$(sensors -u 2>/dev/null | awk -v pat="$CPU_TEMP_CHIP_PATTERN" '
        $0 ~ pat {{ inchip=1; next }}
        inchip && /^$/ {{ inchip=0 }}
        inchip && /temp[0-9]+_input/ {{ print $2; exit }}
    ')"
fi
'''
    footer = _atomic_write_footer(
        "cpu_sensors",
        '    echo "cpu_temp=${CPU_TEMP:-}"',
        '        cpu_temp) echo "${CPU_TEMP:-0}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "cpu_sensors"}) + body + footer


# --------------------------------------------------------------- GPU stats
def gen_gpu_stats_script(project: Project) -> str:
    props = _first_node_props(project, "gpu_stats")
    amd_card_override = props.get("amd_drm_card", "")

    body = f'''
GPU_DRM_CARD={_sh_sq(amd_card_override)}

GPU_STATUS="none"
GPU_UTIL=""; GPU_TEMP=""; GPU_VRAM_USED=""; GPU_VRAM_TOTAL=""

# Conky's own launch context sometimes has a more restricted PATH than an
# interactive shell even when nvidia-smi is genuinely installed, so fall
# back to the usual install locations directly if the PATH lookup misses.
NVIDIA_SMI_BIN="$(command -v nvidia-smi 2>/dev/null)"
if [[ -z "$NVIDIA_SMI_BIN" ]]; then
    for cand in /usr/bin/nvidia-smi /usr/local/bin/nvidia-smi /opt/nvidia/bin/nvidia-smi; do
        [[ -x "$cand" ]] && NVIDIA_SMI_BIN="$cand" && break
    done
fi

if [[ -n "$NVIDIA_SMI_BIN" ]]; then
    GPU_LINE="$("$NVIDIA_SMI_BIN" --query-gpu=utilization.gpu,temperature.gpu,memory.used,memory.total \\
                --format=csv,noheader,nounits 2>/dev/null | head -n1)"
    if [[ "$GPU_LINE" =~ ^[0-9] ]]; then
        IFS=',' read -r GPU_UTIL GPU_TEMP GPU_VRAM_USED GPU_VRAM_TOTAL <<< "$GPU_LINE"
        GPU_UTIL="${{GPU_UTIL// /}}"; GPU_TEMP="${{GPU_TEMP// /}}"
        GPU_VRAM_USED="${{GPU_VRAM_USED// /}}"; GPU_VRAM_TOTAL="${{GPU_VRAM_TOTAL// /}}"
        GPU_STATUS="ok"
    fi
fi

if [[ "$GPU_STATUS" != "ok" ]]; then
    # AMD via sysfs. card0 isn't always the right GPU on a hybrid/multi-GPU
    # system -- override GPU_DRM_CARD above if auto-detection (first card
    # with a gpu_busy_percent file) picks the wrong one.
    CARD="$GPU_DRM_CARD"
    if [[ -z "$CARD" ]]; then
        for c in /sys/class/drm/card*/device/gpu_busy_percent; do
            [[ -f "$c" ]] || continue
            CARD="$(basename "$(dirname "$(dirname "$c")")")"
            break
        done
    fi
    if [[ -n "$CARD" && -f "/sys/class/drm/${{CARD}}/device/gpu_busy_percent" ]]; then
        GPU_UTIL="$(cat "/sys/class/drm/${{CARD}}/device/gpu_busy_percent" 2>/dev/null)"
        for hw in "/sys/class/drm/${{CARD}}/device/hwmon/hwmon"*/temp1_input; do
            [[ -f "$hw" ]] || continue
            GPU_TEMP="$(( $(cat "$hw") / 1000 ))"
            break
        done
        if [[ -f "/sys/class/drm/${{CARD}}/device/mem_info_vram_used" ]]; then
            GPU_VRAM_USED="$(( $(cat "/sys/class/drm/${{CARD}}/device/mem_info_vram_used") / 1048576 ))"
            GPU_VRAM_TOTAL="$(( $(cat "/sys/class/drm/${{CARD}}/device/mem_info_vram_total") / 1048576 ))"
        fi
        [[ -n "$GPU_UTIL" ]] && GPU_STATUS="ok"
    fi
fi
'''
    footer = _atomic_write_footer(
        "gpu_stats",
        '    echo "gpu_status=${GPU_STATUS}"\n'
        '    echo "gpu_util=${GPU_UTIL:-0}"\n'
        '    echo "gpu_temp=${GPU_TEMP:-0}"\n'
        '    echo "gpu_vram_used=${GPU_VRAM_USED:-0}"\n'
        '    echo "gpu_vram_total=${GPU_VRAM_TOTAL:-0}"',
        '        gpu_util) echo "${GPU_UTIL:-0}" ;;\n'
        '        gpu_temp) echo "${GPU_TEMP:-0}" ;;\n'
        '        gpu_vram_used) echo "${GPU_VRAM_USED:-0}" ;;\n'
        '        gpu_vram_total) echo "${GPU_VRAM_TOTAL:-0}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "gpu_stats"}) + body + footer


# --------------------------------------------------------------- Disk sensors
def gen_disk_sensors_script(project: Project) -> str:
    props = _first_node_props(project, "disk_sensors")
    device = props.get("device", "/dev/sda")

    body = f'''
DISK_DEVICE={_sh_sq(device)}

DISK_TEMP=""
if command -v smartctl >/dev/null 2>&1; then
    DISK_TEMP="$(smartctl -A "$DISK_DEVICE" 2>/dev/null | \\
        awk '/Temperature_Celsius|Airflow_Temperature_Cel/ {{print $10; exit}}')"
fi
'''
    footer = _atomic_write_footer(
        "disk_sensors",
        '    echo "disk_temp=${DISK_TEMP:-}"',
        '        disk_temp) echo "${DISK_TEMP:-0}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "disk_sensors"}) + body + footer


# --------------------------------------------------------------- Fan RPM
def gen_fan_sensors_script(project: Project) -> str:
    body = '''
FAN_RPM=""
for hw in /sys/class/hwmon/hwmon*/fan1_input; do
    [[ -f "$hw" ]] || continue
    v="$(cat "$hw" 2>/dev/null)"
    if [[ -n "$v" && "$v" != "0" ]]; then
        FAN_RPM="$v"
        break
    fi
done
'''
    footer = _atomic_write_footer(
        "fan_sensors",
        '    echo "fan_rpm=${FAN_RPM:-0}"',
        '        fan_rpm) echo "${FAN_RPM:-0}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "fan_sensors"}) + body + footer


# --------------------------------------------------------------- Public IP
def gen_public_ip_script(project: Project) -> str:
    body = '''
TIMEOUT=6
IP="$(curl -fsS --max-time "$TIMEOUT" https://icanhazip.com 2>/dev/null | tr -d '[:space:]')"
if [[ -z "$IP" ]]; then
    IP="$(curl -fsS --max-time "$TIMEOUT" https://ifconfig.me 2>/dev/null | tr -d '[:space:]')"
fi
'''
    footer = _atomic_write_footer(
        "public_ip",
        '    echo "ip=${IP:-unknown}"',
        '        ip) echo "${IP:-unknown}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "public_ip"}) + body + footer


# --------------------------------------------------------------- Weather
def gen_weather_script(project: Project) -> str:
    props = _first_node_props(project, "weather")
    fallback = props.get("fallback_location", "")

    body = f'''
FALLBACK_LOCATION={_sh_sq(fallback)}
TIMEOUT=6
FORMAT='%l|%C|%t|%f|%h|%w|%p'

fetch() {{
    local location="$1"
    curl -fsS --max-time "$TIMEOUT" -A "curl" "wttr.in/${{location}}?format=${{FORMAT}}" 2>/dev/null
}}

looks_bad() {{
    local s="$1"
    [[ -z "$s" ]] && return 0
    [[ "$s" == *"Unknown location"* ]] && return 0
    [[ "$s" == *"ERROR"* ]] && return 0
    [[ "$s" == *"<html"* ]] && return 0
    return 1
}}

# Category derived from the condition text -- same case-statement logic
# as skyrim_weather.sh, so an Image/Icon or Weather Icon node can be
# driven by category without needing the flavor-text remapping.
categorize() {{
    local c
    c="$(tr '[:upper:]' '[:lower:]' <<< "$1")"
    case "$c" in
        *clear*|*sunny*) echo "clear" ;;
        *overcast*) echo "overcast" ;;
        *partly*cloud*|*mostly*cloud*|*mostly*sunny*|*cloud*) echo "cloud" ;;
        *freezing*fog*|*mist*|*haze*|*fog*) echo "fog" ;;
        *wind*|*breez*|*gale*) echo "wind" ;;
        *heavy*rain*|*thunder*|*storm*) echo "storm" ;;
        *rain*|*drizzle*|*shower*) echo "rain" ;;
        *blizzard*|*heavy*snow*|*snow*|*sleet*|*ice*) echo "snow" ;;
        *frost*|*cold*) echo "cold" ;;
        *smoke*|*ash*|*dust*|*sand*) echo "dust" ;;
        *hot*) echo "hot" ;;
        *) echo "unknown" ;;
    esac
}}

RESULT="$(fetch "")"
if looks_bad "$RESULT" && [[ -n "$FALLBACK_LOCATION" ]]; then
    RESULT="$(fetch "$FALLBACK_LOCATION")"
fi

STATUS="fail"
CITY=""; COND=""; TEMP_F=""; FEELS=""; HUMID=""; WIND=""; PRECIP=""; CATEGORY="unknown"
if ! looks_bad "$RESULT"; then
    IFS='|' read -r CITY COND TEMP_F FEELS HUMID WIND PRECIP <<< "$RESULT"
    CATEGORY="$(categorize "$COND")"
    STATUS="ok"
fi
'''
    footer = _atomic_write_footer(
        "weather",
        '    echo "status=${STATUS}"\n'
        '    echo "city=${CITY}"\n'
        '    echo "condition=${COND}"\n'
        '    echo "category=${CATEGORY}"\n'
        '    echo "temp_f=${TEMP_F//[^0-9.-]/}"\n'
        '    echo "feels=${FEELS}"\n'
        '    echo "humidity=${HUMID}"\n'
        '    echo "wind=${WIND}"\n'
        '    echo "precip=${PRECIP}"',
        '        condition) echo "${COND:-Unknown}" ;;\n'
        '        category) echo "${CATEGORY:-unknown}" ;;\n'
        '        temp_f) echo "${TEMP_F//[^0-9.-]/}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "weather"}) + body + footer


# --------------------------------------------------------------- Now Playing
def gen_nowplaying_script(project: Project) -> str:
    props = _first_node_props(project, "nowplaying")
    player = props.get("player", "spotify")

    body = f'''
PLAYER={_sh_sq(player)}

STATUS_RAW="$(playerctl -p "$PLAYER" status 2>/dev/null)"
STATUS="stopped"
TITLE=""; ARTIST=""; ALBUM=""; PROGRESS_PCT="0"

if [[ "$STATUS_RAW" == "Playing" || "$STATUS_RAW" == "Paused" ]]; then
    STATUS="$(tr '[:upper:]' '[:lower:]' <<< "$STATUS_RAW")"
    TITLE="$(playerctl -p "$PLAYER" metadata xesam:title 2>/dev/null)"
    ARTIST="$(playerctl -p "$PLAYER" metadata artist 2>/dev/null)"
    ALBUM="$(playerctl -p "$PLAYER" metadata album 2>/dev/null)"

    POS_US="$(playerctl -p "$PLAYER" metadata --format '{{{{position}}}}' 2>/dev/null)"
    LEN_US="$(playerctl -p "$PLAYER" metadata mpris:length 2>/dev/null)"
    if [[ -n "$POS_US" && -n "$LEN_US" && "$LEN_US" -gt 0 ]] 2>/dev/null; then
        PROGRESS_PCT="$(awk -v p="$POS_US" -v l="$LEN_US" 'BEGIN {{ printf "%.0f", (100 * p / l) }}')"
    fi
fi
'''
    footer = _atomic_write_footer(
        "nowplaying",
        '    echo "status=${STATUS}"\n'
        '    echo "title=${TITLE}"\n'
        '    echo "artist=${ARTIST}"\n'
        '    echo "album=${ALBUM}"\n'
        '    echo "progress_pct=${PROGRESS_PCT}"',
        '        status) echo "${STATUS}" ;;\n'
        '        title) echo "${TITLE}" ;;\n'
        '        artist) echo "${ARTIST}" ;;\n'
        '        album) echo "${ALBUM}" ;;\n'
        '        progress_pct) echo "${PROGRESS_PCT:-0}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": "nowplaying"}) + body + footer


# --------------------------------------------------------------- Album Art
def gen_album_art_script(node_id: str, player: str, fallback_path: str) -> str:
    """Per-instance (not family-shared, like Custom Script) -- adapted from
    fetch-art2.sh's streaming-art path (playerctl artUrl -> curl). The
    original's local-file ffmpeg-extraction branch isn't replicated here
    (an extra dependency for a narrower case); falls back to fallback_path
    instead when there's no streaming art URL to fetch."""
    out_name = f"album_art_{node_id}.png"
    fallback_line = f'FALLBACK={_sh_sq(fallback_path)}' if fallback_path else 'FALLBACK=""'
    return f'''#!/usr/bin/env bash
# Generated by Conky Studio -- simplified from fetch-art2.sh (streaming art only).
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
CACHE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/.runtime-cache"
OUT_IMG="${{CACHE_DIR}}/{out_name}"
{fallback_line}
PLAYER={_sh_sq(player)}

mkdir -p "$CACHE_DIR"

STATUS="$(playerctl -p "$PLAYER" status 2>/dev/null)"
if [[ "$STATUS" != "Playing" && "$STATUS" != "Paused" ]]; then
    [[ -n "$FALLBACK" && -f "$FALLBACK" ]] && cp -f "$FALLBACK" "$OUT_IMG"
    exit 0
fi

ART_URL="$(playerctl -p "$PLAYER" metadata mpris:artUrl 2>/dev/null | sed 's;https://open.spotify.com;http://i.scdn.co;g')"
if [[ -z "$ART_URL" ]]; then
    [[ -n "$FALLBACK" && -f "$FALLBACK" ]] && cp -f "$FALLBACK" "$OUT_IMG"
    exit 0
fi

TMP_IMG="${{OUT_IMG}}.tmp"
if curl -fsS --max-time 4 "$ART_URL" -o "$TMP_IMG" && [[ -s "$TMP_IMG" ]]; then
    mv "$TMP_IMG" "$OUT_IMG"
else
    rm -f "$TMP_IMG"
    [[ -n "$FALLBACK" && -f "$FALLBACK" && ! -f "$OUT_IMG" ]] && cp -f "$FALLBACK" "$OUT_IMG"
fi
'''


# --------------------------------------------------------------- Custom script wrapper
def gen_custom_script_wrapper(node_id: str, inner_script_filename: str) -> str:
    """Wraps an arbitrary user script with the same daemon-mode cache
    harness, without needing to understand what the script does -- it
    just captures stdout as the single `value` key. In execi mode the
    inner script is called directly (see codegen/builder.py), so this
    wrapper is only generated/used for daemon-mode custom sources."""
    family = f"custom_{node_id}"
    body = f'''
INNER="$SCRIPT_DIR/{inner_script_filename}"
VALUE="$("$INNER" 2>/dev/null | head -n1)"
'''
    footer = _atomic_write_footer(
        family,
        '    echo "value=${VALUE}"',
        '        value) echo "${VALUE}" ;;',
    )
    return _SHEBANG_HEADER + (_CACHE_DIR_BOILERPLATE % {"family": family}) + body + footer
