"""
Project -> start.sh.

Structure is the validated start.sh pattern verbatim: re-exec under
setsid so the whole process tree (Conky + every background polling
loop) shares one process group, a PID-file lock so launching twice
cleanly replaces the old instance instead of running two HUDs on top of
each other, then one initial run + one `while true; do sleep N; done`
background loop per daemon-mode script family actually used by the
project. execi-mode families need none of this -- Conky's own caching
handles their polling, which is the whole point of that mode.
"""
from __future__ import annotations

from conkystudio.model.project import Project
from conkystudio.nodes import registry


def daemon_families_used(project: Project) -> dict:
    """family_key -> poll_interval (seconds), for every used source node
    in daemon mode, plus every Album Art node (always daemon-mode -- it
    writes an image file rather than printing a value, so there's no
    execi equivalent). If multiple nodes in a family disagree on
    interval, the shortest one wins (so nobody's data is staler than
    they asked for)."""
    used = {e.src_node for e in project.edges}
    out: dict[str, int] = {}
    for n in project.nodes:
        if n.type == "visual.album_art":
            interval = int(n.props.get("poll_interval", 2))
            if n.id not in out or interval < out[n.id]:
                out[n.id] = interval
            continue
        if n.id not in used:
            continue
        spec = registry.get(n.type)
        if spec.category != "source":
            continue
        if n.props.get("poll_mode") != "daemon":
            continue
        family_key = spec.script_family or n.id
        interval = int(n.props.get("poll_interval", 5))
        if family_key not in out or interval < out[family_key]:
            out[family_key] = interval
    return out


def build_start_sh(project: Project, script_filenames: dict) -> str:
    families = daemon_families_used(project)

    loop_blocks = []
    for family_key, interval in sorted(families.items()):
        filename = script_filenames.get(family_key, f"{family_key}.sh")
        loop_blocks.append(f'"${{DIR}}/scripts/{filename}" &')
    for family_key, interval in sorted(families.items()):
        filename = script_filenames.get(family_key, f"{family_key}.sh")
        loop_blocks.append(
            f'(\n'
            f'    while true; do\n'
            f'        sleep {interval}\n'
            f'        "${{DIR}}/scripts/{filename}"\n'
            f'    done\n'
            f') &'
        )
    loops_text = "\n".join(loop_blocks) if loop_blocks else "# (no daemon-mode sources in this project)"

    lock_name = "".join(ch if ch.isalnum() else "-" for ch in project.name.lower()).strip("-") or "conky-studio-hud"

    return f'''#!/usr/bin/env bash
#
# {project.name} -- start.sh
# ---------------------------------------------------------------
# Generated by Conky Studio. Same single-instance-lock pattern as the
# hand-written Batman/Iron-Man themes: launching this twice cleanly
# replaces the running instance instead of stacking a second one on top,
# and setsid groups Conky + every background poller under one process
# group so stopping the HUD (from the Manager, or this script re-running)
# reliably takes everything with it.
#
# Usage:
#   ~/.config/conky/{project.name}/start.sh
#

if [[ -z "$CONKY_STUDIO_REEXEC" ]]; then
    export CONKY_STUDIO_REEXEC=1
    exec setsid "$0" "$@"
fi

DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
LOCK_FILE="${{XDG_RUNTIME_DIR:-/tmp}}/{lock_name}.pid"

if [[ -f "$LOCK_FILE" ]]; then
    OLD_PID="$(cat "$LOCK_FILE" 2>/dev/null)"
    if [[ -n "$OLD_PID" ]] && kill -0 "$OLD_PID" 2>/dev/null; then
        kill -TERM -- "-$OLD_PID" 2>/dev/null
        sleep 0.4
        kill -KILL -- "-$OLD_PID" 2>/dev/null
    fi
fi
echo $$ > "$LOCK_FILE"

mkdir -p "${{DIR}}/.runtime-cache"
chmod +x "${{DIR}}"/scripts/*.sh 2>/dev/null

{loops_text}

exec conky -c "${{DIR}}/conky.conf"
'''
